version: '3'
services: 
    frontend:
        build: 
            context: .
            dockerfile: dockerfile.dev
        command: npm run start
        container_name: mohit
        ports:
            - "3001:3001"        
        volumes: 
            - ./:/frontend
            - /frontend/node_modules
